name: Release Distributables

on:
  release:
    types:
      - published

jobs:
  build-n-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: pip install wheel
    - name: Build new distributables
      run: python setup.py sdist bdist_wheel
    - name: Post release cleaning
      run: |
        python setup.py clean --all
        # rm dist/*
