name: Sync Fork

on:
  schedule:
    - cron: '7 0 * * *' # every day at 7 minutes past midnight
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: 6ameDev
          base: main
          head: main
          merge_method: rebase
